from __future__ import annotations

import structlog

from src.agents.state import DocumentationState
from src.database import execute
from src.memory.chunking import store_document_chunks
from src.memory.organizational import store_audit_log, store_memory

logger = structlog.get_logger()


def _build_reply_body(state: DocumentationState) -> str:
    """Build the reply comment body for the original source."""
    title = state.get("draft_title", "Untitled")
    doc_type = state.get("doc_type", "unknown")
    confidence = state.get("confidence_score", 0)
    content = state.get("draft_content", "")

    return f"""## Generated Documentation

**Title:** {title}
**Type:** {doc_type}
**Confidence:** {confidence:.0%}

---

{content}

---

*This documentation was automatically generated by [Draftly](https://draftly.ai).*
"""


async def _reply_to_github(state: DocumentationState, metadata: dict) -> None:
    """Reply to a GitHub issue with generated documentation."""
    from src.integrations.github_app import (
        add_issue_labels,
        get_installation_token,
        post_issue_comment,
    )

    installation_id = metadata["installation_id"]
    owner = metadata["owner"]
    repo = metadata["repo"]
    issue_number = metadata["issue_number"]

    token = await get_installation_token(installation_id)
    body = _build_reply_body(state)

    await post_issue_comment(owner, repo, issue_number, body, token)

    labels = [state.get("doc_type", "howto")]
    if state.get("confidence_score", 0) >= 0.7:
        labels.append("high-confidence")
    else:
        labels.append("needs-review")

    await add_issue_labels(owner, repo, issue_number, labels, token)

    logger.info("reply_posted_github", owner=owner, repo=repo, issue=issue_number)


async def _reply_to_slack(state: DocumentationState, metadata: dict) -> None:
    """Reply to a Slack thread with generated documentation."""
    from src.integrations.slack import send_slack_message

    channel = metadata["channel"]
    thread_ts = metadata.get("thread_ts")
    body = _build_reply_body(state)

    await send_slack_message(channel=channel, text=body, thread_ts=thread_ts)

    logger.info("reply_posted_slack", channel=channel)


async def _reply_to_discord(state: DocumentationState, metadata: dict) -> None:
    """Reply to a Discord thread with generated documentation."""
    from src.integrations.discord import send_discord_thread_reply

    raw_thread_id = metadata.get("thread_id") or metadata.get("channel_id")
    if raw_thread_id is None:
        logger.warning("reply_skipped_discord_no_thread_id", metadata=metadata)
        return

    thread_id = str(raw_thread_id)
    body = _build_reply_body(state)

    await send_discord_thread_reply(thread_id=thread_id, content=body)

    logger.info("reply_posted_discord", thread_id=thread_id)


async def publish_node(state: DocumentationState) -> dict:
    org_id = state["org_id"]
    doc_id = state.get("doc_id", "")
    content = state.get("draft_content", "")
    title = state.get("draft_title", "")

    logger.info("publish_started", org_id=org_id, doc_id=doc_id)

    # 1. Update documentation status
    await execute(
        "UPDATE documentation SET status = 'approved', updated_at = now() WHERE id = $1",
        doc_id,
    )

    # 2. Store chunked embeddings for future semantic search
    await store_document_chunks(
        org_id=org_id,
        content_id=doc_id,
        title=title,
        content=content,
        metadata={"doc_type": state.get("doc_type"), "confidence": state.get("confidence_score")},
    )

    # 3. Store in organizational memory
    await store_memory(
        org_id=org_id,
        memory_type="organizational",
        key=title,
        value={
            "doc_id": doc_id,
            "content": content[:1000],
            "doc_type": state.get("doc_type"),
            "confidence": state.get("confidence_score"),
        },
        source="documentation_generation",
        confidence=state.get("confidence_score", 0.5),
    )

    # 4. Store reviewer feedback if present
    if state.get("human_feedback"):
        await store_memory(
            org_id=org_id,
            memory_type="reviewer",
            key=f"review_{doc_id}",
            value={
                "feedback": state["human_feedback"],
                "decision": state.get("human_decision"),
                "doc_title": title,
            },
            source="human_review",
            confidence=1.0,
        )

    # 5. Mark support thread as resolved
    await execute(
        """
        UPDATE support_threads
        SET status = 'resolved', resolution = $1, resolved_at = now()
        WHERE id = $2
        """,
        content[:2000],
        state.get("support_thread_id"),
    )

    # 6. Audit log
    await store_audit_log(
        org_id=org_id,
        actor="agent",
        action="publish_documentation",
        resource_type="documentation",
        resource_id=doc_id,
        details={"title": title, "confidence": state.get("confidence_score")},
    )

    # 7. Reply to original source
    source = state.get("source", "cli")
    metadata = state.get("source_metadata", {})
    published_urls = [{"platform": "draftly", "doc_id": doc_id}]
    reply_errors = []

    try:
        if source == "github" and metadata:
            await _reply_to_github(state, metadata)
            published_urls.append({"platform": "github", "issue": metadata.get("issue_number")})
        elif source == "slack" and metadata:
            await _reply_to_slack(state, metadata)
            published_urls.append({"platform": "slack", "channel": metadata.get("channel")})
        elif source == "discord" and metadata:
            await _reply_to_discord(state, metadata)
            published_urls.append({"platform": "discord", "thread": metadata.get("thread_id")})
    except Exception as e:
        reply_errors.append({"platform": source, "error": str(e)})
        logger.error("reply_failed", source=source, error=str(e))

    logger.info("publish_completed", doc_id=doc_id, title=title, source=source)

    return {
        "published_urls": published_urls,
        "reply_errors": reply_errors,
        "human_decision": "",
        "human_feedback": "",
    }
