"""GitHub pipeline runner for processing issues through the LangGraph pipeline."""

from __future__ import annotations

import httpx
import structlog
from langchain_cockroachdb import AsyncCockroachDBSaver

from src.agents.graph import build_graph
from src.agents.state import DocumentationState
from src.config import settings
from src.integrations.github_app import get_installation_token
from src.memory.organizations import get_or_create_org

logger = structlog.get_logger()


def build_github_state(payload: dict, org_id: str) -> DocumentationState:
    """Build initial DocumentationState from GitHub issue data."""
    issue = payload["issue"]
    repo = payload["repository"]

    # Combine title and body for the question
    question = f"{issue['title']}\n\n{issue.get('body', '')}"

    return {
        "org_id": org_id,
        "source": "github",
        "channel_id": repo["full_name"],
        "thread_id": str(issue["number"]),
        "question": question,
        # Initialize all other fields to defaults
        "similar_threads": [],
        "existing_docs": [],
        "reviewer_feedback_history": [],
        "semantic_context": [],
        "github_context": [],
        "slack_context": [],
        "knowledge_package": {},
        "draft_content": "",
        "draft_title": "",
        "doc_type": "howto",
        "confidence_score": 0.0,
        "review_result": {},
        "review_feedback": "",
        "human_decision": "",
        "human_feedback": "",
        "published_urls": [],
        "support_thread_id": "",
        "workflow_id": "",
        "doc_id": "",
        "messages": [],
    }


async def run_github_pipeline(payload: dict, installation_token: str):
    """Orchestrate the full Draftly pipeline for a GitHub issue."""
    issue = payload["issue"]
    repo = payload["repository"]
    owner = repo["owner"]["login"]
    repo_name = repo["name"]
    issue_number = issue["number"]

    logger.info(
        "github_pipeline_started",
        owner=owner,
        repo=repo_name,
        issue_number=issue_number,
    )

    try:
        # 1. Get or create organization
        org_id = await get_or_create_org(
            github_org=owner,
            name=owner,
        )

        # 2. Build initial state
        state = build_github_state(payload=payload, org_id=org_id)

        # 3. Compile and run graph
        async with AsyncCockroachDBSaver.from_conn_string(
            settings.cockroachdb_url
        ) as checkpointer:
            graph = build_graph().compile(checkpointer=checkpointer)

            config = {
                "configurable": {
                    "thread_id": f"github-{repo['id']}-{issue_number}"
                }
            }

            # 4. Invoke pipeline
            result = await graph.ainvoke(state, config)

            # 5. Handle HITL interrupt if present
            if result.get("human_decision") == "":
                # Pipeline paused for human review
                logger.info(
                    "pipeline_paused_for_review",
                    owner=owner,
                    repo=repo_name,
                    issue_number=issue_number,
                )
                # Store workflow for later resume (TODO: implement)
            else:
                # Pipeline completed, post results
                await post_github_results(
                    state=result,
                    owner=owner,
                    repo=repo_name,
                    issue_number=issue_number,
                    token=installation_token,
                )

        logger.info(
            "github_pipeline_completed",
            owner=owner,
            repo=repo_name,
            issue_number=issue_number,
        )

    except Exception as e:
        logger.error(
            "github_pipeline_failed",
            owner=owner,
            repo=repo_name,
            issue_number=issue_number,
            error=str(e),
        )
        # Post error comment to GitHub
        await post_error_comment(
            owner=owner,
            repo=repo_name,
            issue_number=issue_number,
            token=installation_token,
            error=str(e),
        )


async def post_github_results(
    state: DocumentationState,
    owner: str,
    repo: str,
    issue_number: int,
    token: str,
):
    """Post pipeline results back to GitHub as comment and labels."""
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
    }

    # 1. Build comment with documentation
    comment_body = f"""## Generated Documentation

**Title:** {state['draft_title']}
**Type:** {state['doc_type']}
**Confidence:** {state['confidence_score']:.0%}

---

{state['draft_content']}

---

*This documentation was automatically generated by [Draftly](https://draftly.ai) from this issue.*
*Review status: {state.get('review_result', {}).get('status', 'pending')}*
"""

    # 2. Post comment
    comment_url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/comments"
    async with httpx.AsyncClient() as client:
        await client.post(comment_url, headers=headers, json={"body": comment_body})

    # 3. Add labels
    labels = [state["doc_type"]]
    if state["confidence_score"] >= 0.7:
        labels.append("high-confidence")
    else:
        labels.append("needs-review")

    label_url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/labels"
    async with httpx.AsyncClient() as client:
        await client.post(label_url, headers=headers, json={"labels": labels})

    logger.info(
        "github_results_posted",
        owner=owner,
        repo=repo,
        issue_number=issue_number,
    )


async def post_error_comment(
    owner: str,
    repo: str,
    issue_number: int,
    token: str,
    error: str,
):
    """Post error comment to GitHub issue."""
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
    }

    comment_body = f"""## Error Processing Issue

An error occurred while processing this issue:

```
{error}
```

Please check the Draftly logs for more details.

---
*This comment was automatically generated by [Draftly](https://draftly.ai)*
"""

    comment_url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/comments"
    async with httpx.AsyncClient() as client:
        await client.post(comment_url, headers=headers, json={"body": comment_body})

    logger.error(
        "error_comment_posted",
        owner=owner,
        repo=repo,
        issue_number=issue_number,
    )
